Repository MemePlace/Frontend, pull requests merged in 2018-04, with the labels that each got.

#29 Fixes Minor Meme Card Styling Issues
  src/app/community/browse/browse.component.html
  src/app/community/browse/browse.component.scss
  src/app/meme-card/meme-card.component.html
Labels: bug

#28 Adds Search Bar and Autocomplete Functionality
  src/app/api/api.module.ts
  src/app/api/search.service.spec.ts
  src/app/api/search.service.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/material/material.module.ts
  src/app/search/header-search/header-search.component.html
  src/app/search/header-search/header-search.component.scss
  src/app/search/header-search/header-search.component.spec.ts
  src/app/search/header-search/header-search.component.ts
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.html
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.scss
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.spec.ts
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.ts
  src/app/search/search-bar/search-bar.component.html
  src/app/search/search-bar/search-bar.component.scss
  src/app/search/search-bar/search-bar.component.spec.ts
  src/app/search/search-bar/search-bar.component.ts
  src/app/search/search.module.ts
  src/app/sidenav/sidenav.component.html
Labels: enhancement

#33 Adds withCredentials Request Option to API Reqs
  src/app/api/base-api.service.ts
Labels: bug

#35 Fixes HTTP Server Error Reference Message
  src/app/api/base-api.service.ts
Labels: bug

#36 Feature/community service
  src/app/api/api.module.ts
  src/app/api/community.service.spec.ts
  src/app/api/community.service.ts
Labels: enhancement, help wanted

#42 Fixes Search Bar Styling
  src/app/header/header.component.html
  src/app/search/search-bar/search-bar.component.html
  src/app/search/search-bar/search-bar.component.scss
  src/app/search/search.module.ts
Labels: bug

#53 Fixes Minor Prod Strict Issues
  src/app/header/header.component.ts
  src/app/search/header-search/header-search.component.html
Labels: bug

#47 Removes matInput from Search Bar
  src/app/search/search-bar/search-bar.component.html
Labels: bug

#44 Hooks Up Community Creation Form to Server
  src/app/api/community.service.ts
  src/app/community/community.module.ts
  src/app/community/create/create.component.html
  src/app/community/create/create.component.scss
  src/app/community/create/create.component.ts
Labels: enhancement

#58 Adds Meme Data Service w/o Dialog
  src/app/api/api.module.ts
  src/app/api/meme.service.spec.ts
  src/app/api/meme.service.ts
  src/app/app.module.ts
  src/app/community/browse/browse.component.html
  src/app/community/browse/browse.component.ts
  src/app/meme-card/meme-card.component.html
  src/app/meme-card/meme-card.component.ts
Labels: enhancement

#46 Adds Route Guard for Authenticated Users
  src/app/api/api.module.ts
  src/app/api/auth-guard.service.spec.ts
  src/app/api/auth-guard.service.ts
  src/app/api/storage.service.spec.ts
  src/app/api/storage.service.ts
  src/app/api/user.service.ts
  src/app/app-routing.module.ts
Labels: enhancement

#61 Fixes/Improves Meme Vote Handling and Adds Error Snackbar on Failed Vote
  src/app/api/base-api.service.ts
  src/app/api/meme.service.ts
  src/app/material/material.module.ts
  src/app/meme-card/meme-card.component.html
  src/app/meme-card/meme-card.component.ts
Labels: bug, enhancement

#67 Forces to Fetch Details upon Start if Logged in
  src/app/api/user.service.ts
Labels: bug

#68 Adds Community Browsing/Front Page View
  src/app/api/community.service.ts
  src/app/api/meme.service.ts
  src/app/api/user.service.ts
  src/app/app-routing.module.ts
  src/app/community/browse/browse.component.html
  src/app/community/browse/browse.component.scss
  src/app/community/browse/browse.component.ts
  src/app/community/community.module.ts
  src/app/community/create/create.component.ts
  src/app/community/details-dialog/details-dialog.component.html
  src/app/community/details-dialog/details-dialog.component.scss
  src/app/community/details-dialog/details-dialog.component.spec.ts
  src/app/community/details-dialog/details-dialog.component.ts
  src/app/community/meme-view/meme-view.component.html
  src/app/community/meme-view/meme-view.component.scss
  src/app/community/meme-view/meme-view.component.spec.ts
  src/app/community/meme-view/meme-view.component.ts
  src/app/community/toolbar/toolbar.component.html
  src/app/community/toolbar/toolbar.component.scss
  src/app/community/toolbar/toolbar.component.spec.ts
  src/app/community/toolbar/toolbar.component.ts
Labels: enhancement

#70 Fixes Observable Distinct Ordering
  src/app/api/user.service.ts
Labels: bug

#73 Caches Memes in Meme Service
  src/app/api/meme.service.ts
Labels: enhancement

#76 Adds Travis Build YML
  .travis.yml
Labels: enhancement

#77 Adds Meme.Place Custom Domain to Travis-CI Build
  .travis.yml
Labels: bug

#81 Fixes Logged In State if Cache DIffered from Endpoint
  src/app/api/user.service.ts
Labels: bug

#82 Forces Meme View to Reload on New Route Params
  src/app/community/browse/browse.component.ts
Labels: bug

#84 Fixes Github SPA Redirects
  .angular-cli.json
  src/404.html
  src/index.html
Labels: bug, high priority

#86 Fixes Prod API Endpoint
  src/app/api/base-api.service.ts
Labels: bug

#87 Adds Meme Layout Algorithm
  src/app/community/meme-view/meme-view.component.html
  src/app/community/meme-view/meme-view.component.scss
  src/app/community/meme-view/meme-view.component.ts
  src/app/meme-card/meme-card.component.html
  src/app/meme-card/meme-card.component.ts
Labels: enhancement

#89 Redirects User to Searched Community
  src/app/search/header-search/header-search.component.html
  src/app/search/header-search/header-search.component.ts
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.html
  src/app/search/mobile-search-dialog/mobile-search-dialog.component.ts
  src/app/search/search-bar/search-bar.component.html
  src/app/search/search-bar/search-bar.component.ts
  src/app/search/search.module.ts
Labels: bug

#96 Adds Sidebar Event Handling and Fixes Meme Layout Calculations
  package-lock.json
  src/app/api/api.module.ts
  src/app/api/sidebar.service.spec.ts
  src/app/api/sidebar.service.ts
  src/app/community/meme-view/meme-view.component.ts
  src/app/sidenav/sidenav.component.ts
Labels: bug, enhancement

#98 Fixes Meme Layout Aspect Ratio Handling
  src/app/community/meme-view/meme-view.component.html
  src/app/community/meme-view/meme-view.component.ts
  src/app/meme-card/meme-card.component.ts
Labels: enhancement

#99 Fixes Canvas toDataURL Zoom Whitespace
  src/app/creation/fabric/fabric.component.ts
Labels: bug

#101 Adds Route Handling for Meme Dialog
  src/app/app-routing.module.ts
  src/app/community/browse/browse.component.ts
  src/app/meme-dialog/meme-dialog.component.ts
Labels: enhancement

#108 Fixes Browse Paginator Losing State
  src/app/community/meme-view/meme-view.component.html
  src/app/community/meme-view/meme-view.component.scss
Labels: bug

#107 Fixes Meme Card Layout Algo on Cards that Have a Larger Action Bar Than the Image Width
  src/app/community/meme-view/meme-view.component.ts
  src/app/meme-card/meme-card.component.html
  src/app/meme-card/meme-card.component.scss
Labels: bug

#109 Adds Community the Meme Was Posted to On Front Page Meme Cards
  src/app/community/meme-view/meme-view.component.html
  src/app/community/meme-view/meme-view.component.ts
  src/app/meme-card/meme-card.component.html
  src/app/meme-card/meme-card.component.scss
  src/app/meme-card/meme-card.component.ts
Labels: enhancement

#106 Adds Canvas Undo/Redo and Saves State in LocalStorage
  src/app/creation/creation.component.html
  src/app/creation/creation.component.scss
  src/app/creation/fabric/fabric.component.html
  src/app/creation/fabric/fabric.component.ts
Labels: enhancement

#111 Ensures Font is Pre-Loaded Before Adding to Canvas
  package.json
  src/app/creation/fabric/fabric.component.ts
  src/app/creation/function-bar/function-bar.component.scss
  src/app/creation/function-bar/function-bar.component.ts
Labels: bug

#112 Enforces Max-Width to Image in Cards on Desktop
  src/app/meme-card/meme-card.component.ts
Labels: bug

#118 Fixes Canvas MouseWheel Zoom on Firefox
  src/app/creation/creation.component.html
Labels: bug

#116 Makes Travis-CI Run Lint Checks as Part of the Build
  .travis.yml
  src/app/creation/fabric/fabric.component.ts
  src/app/meme-card/meme-card.component.ts
Labels: enhancement

#122 Routes through HTTPS Port on API Server
  src/app/api/base-api.service.ts
Labels: enhancement

#126 Adds Text Object Property Editor
  src/app/creation/creation.component.ts
  src/app/creation/creation.module.ts
  src/app/creation/fabric/fabric.component.html
  src/app/creation/fabric/fabric.component.ts
  src/app/creation/function-bar/function-bar.component.html
  src/app/creation/function-bar/function-bar.component.scss
  src/app/creation/function-bar/function-bar.component.ts
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.html
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.scss
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.spec.ts
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.ts
Labels: enhancement

#127 Disables Create Meme Button during Submission
  src/app/creation/creation.component.html
  src/app/creation/creation.component.ts
  src/app/creation/fabric/fabric.component.ts
Labels: bug

#128 Adds Additional Text Toolbar Features
  src/app/creation/creation.module.ts
  src/app/creation/fabric/fabric.component.html
  src/app/creation/fabric/fabric.component.ts
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.html
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.scss
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.ts
Labels: enhancement

#129 Improves Canvas Text Editing
  src/app/community/toolbar/toolbar.component.ts
  src/app/creation/creation.component.html
  src/app/creation/creation.component.ts
  src/app/creation/creation.module.ts
  src/app/creation/fabric/fabric.component.html
  src/app/creation/fabric/fabric.component.ts
  src/app/creation/function-bar/function-bar.component.html
  src/app/creation/function-bar/function-bar.component.scss
  src/app/creation/function-bar/function-bar.component.ts
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.html
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.scss
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.spec.ts
  src/app/creation/text-edit-toolbar/text-edit-toolbar.component.ts
Labels: enhancement
